// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARq3UlRyxEQFIO4Su0yV6SEvIcmBiH2X8',
    appId: '1:226127394464:web:8137d594edb12bc0557bc5',
    messagingSenderId: '226127394464',
    projectId: 'entr-ema',
    authDomain: 'entr-ema.firebaseapp.com',
    storageBucket: 'entr-ema.appspot.com',
    measurementId: 'G-4297V808T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCumbh62s89HX91T4-pMqRx9U3XIH99CTM',
    appId: '1:226127394464:android:2257e8f6cc36f1c3557bc5',
    messagingSenderId: '226127394464',
    projectId: 'entr-ema',
    storageBucket: 'entr-ema.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPzbHG2oeYzWy9IegmiavpUtW6JJpVJo8',
    appId: '1:226127394464:ios:b8c2738f00098e89557bc5',
    messagingSenderId: '226127394464',
    projectId: 'entr-ema',
    storageBucket: 'entr-ema.appspot.com',
    iosBundleId: 'com.ema.entrema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPzbHG2oeYzWy9IegmiavpUtW6JJpVJo8',
    appId: '1:226127394464:ios:e4f77214e419200c557bc5',
    messagingSenderId: '226127394464',
    projectId: 'entr-ema',
    storageBucket: 'entr-ema.appspot.com',
    iosBundleId: 'com.ema.entrema.RunnerTests',
  );
}
